variables:
  MAVEN_OPTS: -Dmaven.repo.local=.m2/repository

image: maven:latest

workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'

stages:
#    - build
    - test


cache:
  paths:
    - .m2/repository
    - target

test_core_persistence:
  stage: test
  tags:
    - docker

  script: 
    - echo "Maven test for core started"
    - "cd chore-manager/core"
    - "mvn compile"
    - "mvn test"

    - "cd ../persistence"
    - "mvn compile"
    - "mvn test"
  

#build_job:
#  stage: build
#  tags:
#    - docker 
#
#  script: 
#    - echo "Maven compile started"
#    - "cd chore-manager"
#    - "mvn install -DskipTests"

#test_core:
#  stage: test
#  tags:
#    - docker 
#
#  script: 
#    - echo "Maven test started"
#    - "cd chore-manager/core"
#    - "mvn compile"
#    - "mvn test"
#  dependencies:
#    - build_job

#test_persistence:
#  stage: test
#  tags:
#    - docker 
#
#  script: 
#    - echo "Maven test started"
#    - "cd chore-manager/persistence"
#    - "mvn compile"
#    - "mvn test"
#  dependencies:
#    - build_job
