variables:
  MAVEN_OPTS: "-Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository"
  MAVEN_CLI_OPTS: "--batch-mode --errors --fail-at-end --show-version"
  CACHE_KEY: $CI_COMMIT_REF_SLUG

image: maven:latest

workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'

# List of stages for jobs, and their execution order
stages:
    - build
    - test
    - install

cache:
  key: $CACHE_KEY
  paths:
   - .m2/repository
   - .sbt
   - target
    
compile:
  stage: build
  allow_failure: false
  tags:
    - docker

  script: 
    - echo "Stage for compiling tests has started"
    - "cd chore-manager"
    - "mvn compile"

test:
  stage: test
  allow_failure: false
  needs: ["compile"]
  tags:
    - docker

  script: 
    - echo "Stage for running tests has started"
    - "cd chore-manager"
    - "mvn test -DskipUITests"

# Runs install
# Also runs Spotbugs, Checkstyle, JaCoCo and JavaDocs
install:
  stage: install
  allow_failure: false
  tags:
    - docker

  script: 
    - echo "Stage for installing application"
    - "cd chore-manager"
    - "mvn clean install -DskipTests"